services:
  qbittorrent-p2p-port-updater:
    build: .
    container_name: qbittorrent-p2p-port-updater
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-5000}:5000"
    env_file:
      - .env
    networks:
      - localnet

